'use client'

import { useMemo, useRef, useState } from 'react'
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { ArrowUpRight, BarChart3, ChevronDown, ChevronLeft, Download, FileText, Filter, Info, LayoutDashboard, Menu, Moon, MoreHorizontal, Plus, Search, Sparkles, Sun, Table2, Upload, X, Zap } from 'lucide-react'

const products = [{ name: 'MacBook Air', value: 186400 }, { name: 'iPhone 15', value: 152800 }, { name: 'iPad Air', value: 98400 }, { name: 'AirPods Pro', value: 74600 }, { name: 'Magic Keyboard', value: 49200 }]
const regions = [{ name: 'Western Cape', value: 312400 }, { name: 'Gauteng', value: 286800 }, { name: 'KwaZulu-Natal', value: 164200 }, { name: 'Eastern Cape', value: 101800 }]
const timeline = [{ name: 'Jan', value: 84000 }, { name: 'Feb', value: 102000 }, { name: 'Mar', value: 98000 }, { name: 'Apr', value: 126000 }, { name: 'May', value: 118000 }, { name: 'Jun', value: 142000 }]
const fields = [['product','text'], ['category','text'], ['revenue','number'], ['quantity','number'], ['order_date','date'], ['region','text'], ['customer','text'], ['sales_rep','text'], ['order_id','text']]
const suggestions = ['What were our top 5 products last month?', 'Show revenue by region.', 'How has revenue changed over time?', 'Which category generated the most revenue?']

type Result = { title: string; meta: string; data: { name: string; value: number }[]; kind: 'bar' | 'line' }

export default function Home() {
  const [started, setStarted] = useState(false)
  const [dark, setDark] = useState(false)
  const [query, setQuery] = useState('')
  const [loading, setLoading] = useState(false)
  const [view, setView] = useState<'chart' | 'table'>('chart')
  const [result, setResult] = useState<Result>({ title: 'Top 5 Products by Revenue', meta: 'Northstar Retail · Last 30 days', data: products, kind: 'bar' })
  const [field, setField] = useState<string | null>(null)
  const [mobileNav, setMobileNav] = useState(false)
  const [filterOpen, setFilterOpen] = useState(false)
  const inputRef = useRef<HTMLInputElement>(null)

  const runQuery = (text: string) => { setQuery(text); setLoading(true); setTimeout(() => { const lower = text.toLowerCase(); if (lower.includes('region')) setResult({ title: 'Revenue by Region', meta: 'Northstar Retail · All time', data: regions, kind: 'bar' }); else if (lower.includes('time') || lower.includes('month')) setResult({ title: 'Revenue Over Time', meta: 'Northstar Retail · January — June 2024', data: timeline, kind: 'line' }); else setResult({ title: 'Top 5 Products by Revenue', meta: 'Northstar Retail · Last 30 days', data: products, kind: 'bar' }); setLoading(false) }, 800) }
  const chartTotal = useMemo(() => result.data.reduce((sum, item) => sum + item.value, 0), [result])

  if (!started) return <Landing onStart={() => setStarted(true)} dark={dark} setDark={setDark} />

  return <main className={dark ? 'app dark' : 'app'}>
    <header className="topbar"><div className="brand"><span className="brand-mark"><Zap size={15} fill="currentColor" /></span>QuickQuery</div><div className="top-actions"><button className="dataset-switch"><FileText size={15} /> Northstar Retail <ChevronDown size={14} /></button><button className="icon-button" aria-label="Toggle theme" onClick={() => setDark(!dark)}>{dark ? <Sun size={17} /> : <Moon size={17} />}</button><button className="share-button">Share</button><button className="icon-button" aria-label="More options"><MoreHorizontal size={18} /></button></div><button className="mobile-menu" aria-label="Open navigation" onClick={() => setMobileNav(true)}><Menu /></button></header>
    <div className="workspace"><aside className={mobileNav ? 'sidebar open' : 'sidebar'}><div className="sidebar-close"><button className="icon-button" onClick={() => setMobileNav(false)}><X /></button></div><div className="side-label">DATASET</div><div className="dataset-name"><span className="file-icon"><FileText size={16} /></span><div><strong>Northstar Retail</strong><span>12,482 rows · 10 columns</span></div></div><div className="side-section"><div className="side-label">FIELDS <span>10</span></div><div className="field-list">{fields.map(([name, type]) => <button key={name} className={field === name ? 'field active' : 'field'} onClick={() => setField(field === name ? null : name)}><span className="field-type">{type === 'number' ? '#' : type === 'date' ? '◷' : 'T'}</span>{name}<Info size={13} /></button>)}</div></div><div className="sidebar-foot"><div className="privacy"><span className="status-dot" /> Local browser session</div><span className="version">MVP preview</span></div></aside><section className="content"><div className="content-inner"><div className="eyebrow"><LayoutDashboard size={15} /> WORKSPACE <span>/</span> NORTHSTAR RETAIL</div><div className="heading-row"><div><h1>Ask your data</h1><p>Explore your dataset with natural language or build a query visually.</p></div><button className="outline-button" onClick={() => inputRef.current?.focus()}><Sparkles size={15} /> Ask a question</button></div><div className="ask-box"><div className="ask-icon"><Search size={18} /></div><input ref={inputRef} value={query} onChange={e => setQuery(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.nativeEvent.isComposing && e.keyCode !== 229 && query.trim()) runQuery(query) }} placeholder="What would you like to know?" aria-label="Ask your data" /><button className="ask-submit" disabled={!query.trim() || loading} onClick={() => runQuery(query)} aria-label="Run query"><ArrowUpRight size={19} /></button></div><div className="ask-hint"><span>Try asking</span>{suggestions.slice(0, 3).map(item => <button key={item} onClick={() => runQuery(item)}>{item}</button>)}</div>{field && <div className="field-inspector"><div><strong>{field}</strong><span>Detected field</span></div><span className="inspector-type">{fields.find(f => f[0] === field)?.[1]}</span><div className="inspector-stat"><span>Unique values</span><strong>{field === 'order_id' ? '12,482' : '248'}</strong></div><div className="inspector-stat"><span>Null values</span><strong>0</strong></div></div>}
      <div className="builder"><div className="builder-head"><div><h2>Visual query</h2><p>Prefer controls? Build your question step by step.</p></div><button className="text-button"><Plus size={15} /> Add filter</button></div><div className="builder-controls"><div className="control"><label>MEASURE</label><button>Revenue <ChevronDown /></button></div><div className="control"><label>AGGREGATION</label><button>Sum <ChevronDown /></button></div><div className="control"><label>GROUP BY</label><button>Product <ChevronDown /></button></div><div className="control"><label>DATE RANGE</label><button>Last 30 days <ChevronDown /></button></div></div></div>
      <div className="results-head"><div><div className="eyebrow result-eyebrow">RESULT</div><h2>{loading ? 'Analyzing your data…' : result.title}</h2><p>{result.meta}</p></div><div className="result-actions"><button className="export-button" onClick={() => alert('Export menu ready for CSV, PNG, and PDF.') }><Download size={15} /> Export <ChevronDown size={14} /></button><div className="view-toggle"><button className={view === 'chart' ? 'selected' : ''} onClick={() => setView('chart')}><BarChart3 size={15} /> Chart</button><button className={view === 'table' ? 'selected' : ''} onClick={() => setView('table')}><Table2 size={15} /> Table</button></div></div></div>
      <div className="result-toolbar"><button onClick={() => setFilterOpen(!filterOpen)}><Filter size={14} /> Filters <span className="filter-count">1</span></button><span className="toolbar-separator" /><span>Showing {result.data.length} rows</span></div>{filterOpen && <div className="filters"><div className="filter-item"><label>Date</label><button>Last 30 days <ChevronDown /></button></div><div className="filter-item"><label>Region</label><button>All regions <ChevronDown /></button></div><div className="filter-item"><label>Category</label><button>All categories <ChevronDown /></button></div></div>}
      {loading ? <div className="loading-state"><div className="spinner" /><strong>Analyzing Northstar Retail…</strong><span>Turning your question into a visual answer</span></div> : view === 'chart' ? <div className="chart-wrap"><div className="chart-summary"><span>Total revenue</span><strong>R {chartTotal.toLocaleString()}</strong></div><ResponsiveContainer width="100%" height={290}>{result.kind === 'line' ? <LineChart data={result.data} margin={{ top: 20, right: 12, left: 5, bottom: 5 }}><CartesianGrid vertical={false} stroke="var(--grid)" /><XAxis dataKey="name" tickLine={false} axisLine={false} tick={{ fill: 'var(--muted)', fontSize: 12 }} /><YAxis tickLine={false} axisLine={false} tick={{ fill: 'var(--muted)', fontSize: 12 }} tickFormatter={v => `R${v / 1000}k`} width={44} /><Tooltip contentStyle={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 8 }} formatter={(v) => [`R ${Number(v).toLocaleString()}`, 'Revenue']} /><Line type="monotone" dataKey="value" stroke="var(--accent)" strokeWidth={2.5} dot={{ fill: 'var(--accent)', r: 4 }} /></LineChart> : <BarChart data={result.data} layout="vertical" margin={{ top: 20, right: 12, left: 8, bottom: 5 }}><CartesianGrid horizontal={false} stroke="var(--grid)" /><XAxis type="number" hide /><YAxis type="category" dataKey="name" tickLine={false} axisLine={false} tick={{ fill: 'var(--text)', fontSize: 12 }} width={100} /><Tooltip cursor={{ fill: 'var(--hover)' }} contentStyle={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 8 }} formatter={(v) => [`R ${Number(v).toLocaleString()}`, 'Revenue']} /><Bar dataKey="value" fill="var(--accent)" radius={[0, 3, 3, 0]} barSize={28} /></BarChart>}</ResponsiveContainer></div> : <div className="table-wrap"><table><thead><tr><th>Rank</th><th>{result.kind === 'line' ? 'Period' : result.title.includes('Region') ? 'Region' : 'Product'}</th><th className="numeric">Revenue</th><th className="numeric">Share</th></tr></thead><tbody>{result.data.map((item, index) => <tr key={item.name}><td className="muted">{String(index + 1).padStart(2, '0')}</td><td><strong>{item.name}</strong></td><td className="numeric">R {item.value.toLocaleString()}</td><td className="numeric muted">{Math.round(item.value / chartTotal * 100)}%</td></tr>)}</tbody></table></div>}
      <div className="result-foot"><span><span className="success-dot" /> Query completed in 0.8s</span><button className="text-button">Edit query <ChevronDown size={14} /></button></div></div></section></div>
  </main>
}

function Landing({ onStart, dark, setDark }: { onStart: () => void; dark: boolean; setDark: (v: boolean) => void }) { return <main className={dark ? 'landing dark' : 'landing'}><header className="landing-header"><div className="brand"><span className="brand-mark"><Zap size={15} fill="currentColor" /></span>QuickQuery</div><nav><a href="#product">Product</a><a href="#how">How it works</a><a href="#sample">Sample dataset</a></nav><div className="landing-actions"><button className="icon-button" onClick={() => setDark(!dark)} aria-label="Toggle theme">{dark ? <Sun size={17} /> : <Moon size={17} />}</button><button className="header-cta" onClick={onStart}>Open QuickQuery <ArrowUpRight size={15} /></button></div></header><section className="hero" id="product"><div className="hero-kicker"><span className="kicker-line" /> CSV-first data exploration</div><h1>Explore your data.<br /><em>Get answers fast.</em></h1><p>Upload a CSV, ask questions in plain language, and turn your data into useful charts without writing SQL.</p><div className="hero-actions"><button className="primary-button" onClick={onStart}><Upload size={17} /> Upload CSV</button><button className="secondary-button" onClick={onStart}>Try sample data <ArrowUpRight size={15} /></button></div><span className="privacy-note"><span className="status-dot" /> Your CSV stays in your browser during exploration.</span></section><section className="workflow" id="how"><div className="workflow-head"><span>How it works</span><span>Four simple steps</span></div><div className="steps">{[['01','Upload','Bring your CSV into a calm, focused workspace.'],['02','Ask','Use plain language to ask questions of your data.'],['03','Explore','Shape the answer with visual controls.'],['04','Export','Take your charts and results with you.']].map(([num,title,copy], i) => <div className="step" key={num}><span className="step-num">{num}</span><div><strong>{title}</strong><p>{copy}</p></div>{i < 3 && <span className="step-arrow">→</span>}</div>)}</div></section><div className="landing-footer"><span>Built for curious teams</span><span className="footer-rule" /><span>Northstar Retail sample dataset</span></div></main>}
